<?php

namespace Payabli\Types;

use Payabli\Core\Json\JsonSerializableType;
use Payabli\Core\Json\JsonProperty;
use Payabli\Core\Types\ArrayType;

class NotificationReportRequestContent extends JsonSerializableType
{
    /**
     * @var ?'Report' $eventType The notification's event name.
     */
    #[JsonProperty('eventType')]
    public ?string $eventType;

    /**
     * @var ?value-of<NotificationReportRequestContentFileFormat> $fileFormat Indicate the format of report file to be generated by the engine.
     */
    #[JsonProperty('fileFormat')]
    public ?string $fileFormat;

    /**
     * @var ?array<KeyValueDuo> $internalData Array of pairs key:value to insert in request body to target in **method** = *report-web*.
     */
    #[JsonProperty('internalData'), ArrayType([KeyValueDuo::class])]
    public ?array $internalData;

    /**
     * @var ?value-of<NotificationReportRequestContentReportName> $reportName The kind report to generate.
     */
    #[JsonProperty('reportName')]
    public ?string $reportName;

    /**
     * @var ?int $timeZone
     */
    #[JsonProperty('timeZone')]
    public ?int $timeZone;

    /**
     * @var ?string $transactionId Used internally to reference the entity or object generating the event.
     */
    #[JsonProperty('transactionId')]
    public ?string $transactionId;

    /**
     * @var ?array<KeyValueDuo> $webHeaderParameters Array of pairs key:value to insert in header of request to target in **method** = *report-web*.
     */
    #[JsonProperty('webHeaderParameters'), ArrayType([KeyValueDuo::class])]
    public ?array $webHeaderParameters;

    /**
     * @param array{
     *   eventType?: ?'Report',
     *   fileFormat?: ?value-of<NotificationReportRequestContentFileFormat>,
     *   internalData?: ?array<KeyValueDuo>,
     *   reportName?: ?value-of<NotificationReportRequestContentReportName>,
     *   timeZone?: ?int,
     *   transactionId?: ?string,
     *   webHeaderParameters?: ?array<KeyValueDuo>,
     * } $values
     */
    public function __construct(
        array $values = [],
    ) {
        $this->eventType = $values['eventType'] ?? null;
        $this->fileFormat = $values['fileFormat'] ?? null;
        $this->internalData = $values['internalData'] ?? null;
        $this->reportName = $values['reportName'] ?? null;
        $this->timeZone = $values['timeZone'] ?? null;
        $this->transactionId = $values['transactionId'] ?? null;
        $this->webHeaderParameters = $values['webHeaderParameters'] ?? null;
    }

    /**
     * @return string
     */
    public function __toString(): string
    {
        return $this->toJson();
    }
}
